<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/04/14 15:20:08

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=jobeet;host=localhost',
  'username' => 'root',
  'password' => 'pa$$',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
